* Use 3 dataframes criados na aula anterior, mostre apenas o filme/série/anime com maior pontuação.
* Leia o arquivo do dataset em json.
* Selecione apenas as 3 primeiras colunas do dataset
* Selecione apenas as 10 primeiras linhas do dataset
* Filtre o dataframe pegando apenas as linhas com valores maiores que essa média.
* Escolha uma coluna com valores textuais e filtre o dataframe pelo 1º valor
* Escolha uma coluna, como ano, titulo, etc e ordene seu dataframe tanto de forma crescente quanto decrescente

In [6]:
import pandas as pd

df_filmes = pd.read_json('../../aula_03/exercício_07/Filmes.json')
df_series = pd.read_json('../../aula_03/exercício_07/Séries.json')
df_desenhos = pd.read_json('../../aula_03/exercício_07/Desenhos.json')

df_geral = pd.concat([df_filmes, df_series, df_desenhos]).reset_index(drop=True)
df_geral

                                      Título  Ano de lançamento  Nota
0   Os Feiticeiros de Waverly Place: O Filme               2009  10.0
1         Velozes e Furiosos 5: Operação Rio               2011   9.5
2                    Os Vingadores: Ultimato               2019  10.0
3                                Escape Room               2019   8.5
4                                   Rei Leão               1994  10.0
5                        The Vampire Diaries               2009  10.0
6                               Supernatural               2005   9.0
7               Feiticeiros de Waverly Place               2007  10.0
8                                         3%               2016   8.0
9                                Wandavision               2021   9.5
10                                   Pokémon               1997   8.0
11                               Bob Esponja               1999  10.0
12                             Danny Phantom               2004   9.5
13                   KND - A turma do bairro               2002   8.5
14                            Phineas e Ferb               2007   9.0

In [7]:
df_melhores = df_geral[df_geral['Nota'] == max(df_geral['Nota'])]
df_melhores

                                      Título  Ano de lançamento  Nota
0   Os Feiticeiros de Waverly Place: O Filme               2009  10.0
2                    Os Vingadores: Ultimato               2019  10.0
4                                   Rei Leão               1994  10.0
5                        The Vampire Diaries               2009  10.0
7               Feiticeiros de Waverly Place               2007  10.0
11                               Bob Esponja               1999  10.0

In [8]:
df_geral.head(10)

                                     Título  Ano de lançamento  Nota
0  Os Feiticeiros de Waverly Place: O Filme               2009  10.0
1        Velozes e Furiosos 5: Operação Rio               2011   9.5
2                   Os Vingadores: Ultimato               2019  10.0
3                               Escape Room               2019   8.5
4                                  Rei Leão               1994  10.0
5                       The Vampire Diaries               2009  10.0
6                              Supernatural               2005   9.0
7              Feiticeiros de Waverly Place               2007  10.0
8                                        3%               2016   8.0
9                               Wandavision               2021   9.5

In [10]:
df_acima_media = df_geral[df_geral['Nota'] > df_geral['Nota'].mean()]
df_acima_media

                                      Título  Ano de lançamento  Nota
0   Os Feiticeiros de Waverly Place: O Filme               2009  10.0
1         Velozes e Furiosos 5: Operação Rio               2011   9.5
2                    Os Vingadores: Ultimato               2019  10.0
4                                   Rei Leão               1994  10.0
5                        The Vampire Diaries               2009  10.0
7               Feiticeiros de Waverly Place               2007  10.0
9                                Wandavision               2021   9.5
11                               Bob Esponja               1999  10.0
12                             Danny Phantom               2004   9.5